// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAraWnd64H_NJLdOI4AwPEmE5q7tVz3yr8',
    appId: '1:853245591672:web:9f2e2ed7ff593831612d8d',
    messagingSenderId: '853245591672',
    projectId: 'mallbuddy-51690',
    authDomain: 'mallbuddy-51690.firebaseapp.com',
    storageBucket: 'mallbuddy-51690.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU71nDFWIkmi1TdFXpBV0u9WzjUZm71ms',
    appId: '1:853245591672:android:b5a33f0adf77bb19612d8d',
    messagingSenderId: '853245591672',
    projectId: 'mallbuddy-51690',
    storageBucket: 'mallbuddy-51690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjhsIIfR0zvNh33h6yl2IY_2olR9gNdE',
    appId: '1:853245591672:ios:198cb90277703e53612d8d',
    messagingSenderId: '853245591672',
    projectId: 'mallbuddy-51690',
    storageBucket: 'mallbuddy-51690.firebasestorage.app',
    iosBundleId: 'com.example.mallBud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARjhsIIfR0zvNh33h6yl2IY_2olR9gNdE',
    appId: '1:853245591672:ios:198cb90277703e53612d8d',
    messagingSenderId: '853245591672',
    projectId: 'mallbuddy-51690',
    storageBucket: 'mallbuddy-51690.firebasestorage.app',
    iosBundleId: 'com.example.mallBud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAraWnd64H_NJLdOI4AwPEmE5q7tVz3yr8',
    appId: '1:853245591672:web:7f3f53f6b3efd025612d8d',
    messagingSenderId: '853245591672',
    projectId: 'mallbuddy-51690',
    authDomain: 'mallbuddy-51690.firebaseapp.com',
    storageBucket: 'mallbuddy-51690.firebasestorage.app',
  );
}
